config/routes.rb
Samaraparts::Application.routes.draw do
	# Authentication
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"  
  
	resources :users  
	resources :sessions
	resources :requests
	resources :feedbacks

	root :to => "welcome#index"
	
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  
  validates :full_name, :presence => true
  validates :title, :presence => true
  validates :body, :presence => true  
  
  def self.find(*args)
    if args.first.to_s == "random"
      ids = connection.select_all("SELECT id FROM feedbacks")
      super(ids[rand(ids.length)]["id"].to_i)
    else
      super
    end
  end
  
end

app/models/request.rb
class Request < ActiveRecord::Base
	attr_accessible :mark, :car_model, :year, :displacement, :vin, :engine_model, :required_part, :client_name, :client_phone
	
	validates :mark, 					:presence => true
	validates :car_model, 		:presence => true
	# validates :year, 					:presence => true
	# validates :displacement, 	:presence => true
	validates :vin, 					:presence => true
	# validates :engine_model, 	:presence => true
	validates :required_part, :presence => true
	validates :client_name, 	:presence => true
	validates :client_phone, 	:presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :login, :password, :password_confirmation
	
	attr_accessor :password
	before_save :encrypt_password

	validates :login, :presence => true, :uniqueness => true
	validates_presence_of :password, :on => :create
	validates :password, :confirmation => true
	
	def self.authenticate(login, password)
		user = find_by_login(login)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
	
end

app/controllers/application_controller.rb
#coding: utf-8

class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user  
  
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def deny_access(flash_message = nil)
    flash[:alert] = flash_message if flash_message
    redirect_to(root_url)
  end
  
  def authenticate
    deny_access("Доступ запрещен.") unless signed_in?
  end
  
  def signed_in?
    ! current_user.nil?
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_filter :authenticate
  before_filter :show_picture_preview, :only => [:edit, :update]

  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @feedback = Feedback.find(params[:id])
  end

  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to(feedbacks_url, :notice => t("feedbacks.create_succeed")) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to(feedbacks_url, :notice => t("feedbacks.update_succeed")) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to(root_url, :notice => t("feedbacks.destroy_success")) }
    end
  end
  
  private
  
    def show_picture_preview
      @show_picture_preview = true
    end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
  	@request = Request.new
  end
  
  def create
  	@request = Request.new(params[:request])
  	if @request.save
  		UserMailer.part_request(@request).deliver
  		redirect_to @request, :notice => t("requests.create_succeed")
		else
			redirect_to root_url, :notice => t("requests.create_failed")
		end
  end
  
  def show  	
  end

end

app/controllers/sessions_controller.rb
#coding: utf-8

class SessionsController < ApplicationController
  def new
  end
  
  def create
  	user = User.authenticate(params[:session][:login], params[:session][:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice => t("sessions.create_succeed")
		else
			flash.now.alert = t("sessions.create_failed")
			render "new"
		end
  end
  
  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, :notice => t("sessions.destroy_succeed")
  end

end

app/controllers/users_controller.rb
#coding: utf-8

class UsersController < ApplicationController
  def new
  	@user = User.new
  end
	
  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to root_url, :notice => t("users.create_succeed")
		else
			render "new"
		end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@request = Request.new
  	@request.year = Time.now.year
    @feedbacks = Feedback.find(:all, :order => "random()", :limit => 3)
    @cars = ['big_blue', 'pretty_red', 'little_salate']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/feedbacks/_inputs.html.haml
= simple_form_for @feedback, :html => { :multipart => true } do |f|
  .inputs
    = f.input :full_name, :label => "Имя и фамилия", :required => false
    = f.input :title, :label => "Должность и место работы", :required => false
    
    = f.input :picture, :label => "Фотография", :as => :file, :required => false
    = f.input :picture_cache, :as => :hidden
    - if @show_picture_preview
      .picture_preview
        = image_tag @feedback.picture_url(:thumb) if @feedback.picture?
          
    = f.input :body, :label => "Содержание", :required => false
  .actions
    = f.submit "Сохранить"

app/views/feedbacks/edit.html.haml
- title "Редактирование отзыва"

%h1 Редактирование отзыва

= render 'inputs'
%br/
= link_to 'Назад', feedbacks_path

app/views/feedbacks/index.html.haml
- title "Все отзывы"

%h1 Все отзывы

%table
  %thead
    %tr
      %th{:width => "15%"} Имя
      %th{:width => "20%"} Должность
      %th{:width => "55%"} Содержание
      %th{:width => "10%"}
  %tbody
    - @feedbacks.each do |feedback|
      %tr
        %td.name
          %span= feedback.full_name
          .photo
            = image_tag feedback.picture_url(:thumb) if feedback.picture?
        %td= feedback.title
        %td= feedback.body
        %td
          = link_to 'Изменить', edit_feedback_path(feedback), :style => "color: #060;"
          %br/
          = link_to 'Удалить', feedback, :style => "color: red;", :confirm => 'Вы уверены?', :method => :delete

%br

= link_to 'Новый отзыв', new_feedback_path

app/views/feedbacks/new.html.haml
- title "Новый отзыв"

%h1 Новый отзыв

= render 'inputs'
%br/
= link_to 'Назад', feedbacks_path

app/views/feedbacks/show.html.haml
%p#notice= notice

%p
  %b Full name:
  = @feedback.full_name
%p
  %b Title:
  = @feedback.title
%p
  %b Body:
  = @feedback.body

= link_to 'Edit', edit_feedback_path(@feedback)
\|
= link_to 'Back', feedbacks_path

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en-US"}
	%head
		%meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
		%title
			= yield (:title)
		= stylesheet_link_tag "application"
		= javascript_include_tag "jquery.min", "jquery.hotkeys", "jquery.facebox", "application", "rails"
		= csrf_meta_tag
	%body
		= render :partial => "application/metrika"
		- if params[:controller] == "welcome"
			#new_request_form{:style => "display: none;"}
				= render :partial => "requests/form"
		= render :partial => "shared/flashes"
		.page-header-wrap
			.page-header
				#logo
					= link_to_unless_current(image_tag("logo.png"), root_url)
				#phone
					%h4 телефон для справок
					%span (846) 922-69-95
				#statements
					%h1 Мы — это:
					%ul
						%li Широкий спектр автомобильных запчастей европейских, японских и корейских производителей.
						%li Оригинал и достойные аналоги.
						%li Поставки из Москвы, С.Петербурга, Н.Новгорода и Самары.
						%li Багажники, фаркопы, защита двигателя.
						%li Оптимальные цены.
						%li Возможность доставки по городу.
			
		.border
		- if params[:controller] == "welcome"
			.page-special-wrap
				.page-special.columns
					.special-header
						%h3 Специальные предложения
						- if current_user
							%span= link_to "Все отзывы", feedbacks_url
					- @feedbacks.each_with_index do |feedback, i|
						.column.x1
							.inner
								.special-photo
									%span.round_picture{:style => "height: 58px; width: 58px;"}
										= image_tag feedback.picture_url(:thumb), :height => 58, :width => 58, :alt => feedback.full_name
								.special-content
									.special-content-name
										%h6= feedback.full_name
									.special-content-title
										= feedback.title
									.special-content-quote
										= surround '«', '»' do
											= feedback.body
									%div{:class => "pixel-car #{@cars[i]}"}
		
		.page-content-wrap
			.page-content	
				- if current_user
					= link_to "Выйти", logout_path		
				= yield
				
				%div{:style => "margin-top: 1em;"}
					= render "/shared/li"
			
		.page-footer-wrap
			.page-footer
				.columns
					.column.x1
						.inner
							%ul
								%li 
									Электропочта:
									= mail_to "info@samaraparts.ru"
								%li
									= link_to_unless_current "Адреса и телефоны", page_path("contacts")
					.copyright.column.x1
						.inner
							%i
							.made_by
								Site by
								= link_to "Adam Miribyan", "http://adammiribyan.com"
								%small 2011

app/views/pages/contacts.html.haml
- title 'Контактная информация | Автомастер'

%h1 Контактная информация

.columns.page
  .column.f-x2
    %h3 Схема проезда
    = render "shared/map"
  .column.f-x1{:style => "margin-top: 0.9em;"}
    %div{:style => "margin-bottom: 2.333em;"}
      %h4 Адрес
      Южный проезд, 164
    %div{:style => "margin-bottom: 2.333em;"}
      %h4 Телефон
      (846) 922-69-95
    %div{:style => "margin-bottom: 2.333em;"}
      %h4 График работы
      %p 
        C понедельника по пятницу с 9 до 18 часов.
        %br/
        Cуббота — с 9 до 16 часов.
    

app/views/requests/_form.html.haml
%h2 Новая заявка	
= simple_form_for @request do |f|	
	= f.hint "Все поля обязательны для заполнения.", :style => "margin-bottom: 15px;"
	.columns
		.column.x2
			= f.input :mark, :label => "Марка автомобиля", :required => false
			= f.input :car_model, :label => "Модель", :required => false
			= f.input :year, :label => "Год", :required => false
			= f.input :displacement, :label => "Объем двигателя", :required => false
			= f.input :engine_model, :label => "Модель двигателя", :required => false
		.column.x2
			= f.input :vin, :label => "VIN-код", :required => false
			= f.input :required_part, :label => "Требуемая деталь", :required => false
			%hr
			= f.input :client_name, :label => "Имя и фамилия", :required => false
			= f.input :client_phone, :label => "Телефон", :required => false
	.actions
		= f.submit "Отправить"

app/views/requests/new.html.haml
%h1 Requests#new
%p Find me in app/views/requests/new.html.haml

app/views/requests/show.html.haml
- title "Заявка принята"
%h1 Ваша заявка успешно принята!

app/views/shared/_flashes.html.haml
- flash.each do |key, value|
  = content_tag :div, html_escape(value), :id => "flash_#{key}"

app/views/users/new.html.haml
- title "Регистрация"

%h1 Регистрация нового пользователя

= simple_form_for @user do |f|
	= f.input :login, :label => "Логин", :required => false
	= f.input :password, :label => "Пароль", :as => :password, :required => false
	= f.input :password_confirmation, :label => "Еще раз", :as => :password, :required => false
	= f.submit "Зарегистрироваться"

app/views/welcome/index.html.haml
- title "Запчасти для иномарок | Автомастер Самара"

.columns
	.column.x1
		.inner
			%h4 Срочно нужна помощь
			%p 
				Заполните специальную форму и отправьте нам заявку. 
				%br/
				После этого мы вам позвоним и расскажем вам как можно будет в короткие сроки получить нужную деталь. 			
			= link_to image_tag("btn_fill-request.png"), "#new_request_form", :rel => "facebox[.part_request]"
	.column.x1
		.inner
			%h4 Как до нас добраться
			%p
				Наш офис находится по адресу
				= succeed "." do
					%strong Южный проезд, 164
				%br/
				Мы работаем с понедельника по пятницу 
				%span.nobr с 9 до 18, 
				в субботу — 
				%span.nobr с 9 до 16 часов.
			%p
				Более подробно об этом на странице 
				= succeed "." do
					= link_to "контактной информации", page_path("contacts")
	.column.x1
		.inner
			%h4 Мы в соцмедиа
			%p Следите за нашими новостями.
			.social_bar
				%a{:href => ""}
					= image_tag "social/flickr.png", :height => 16, :width => 16, :class => "normal"
					= image_tag "social/flickr_disabled.png",  :height => 16, :width => 16, :class => "disabled"
				%a{:href => ""}
					= image_tag "social/twitter.png", :height => 16, :width => 16, :class => "normal"
					= image_tag "social/twitter_disabled.png",  :height => 16, :width => 16, :class => "disabled"
				%a{:href => ""}
					= image_tag "social/vkontakte.png", :height => 16, :width => 16, :class => "normal"
					= image_tag "social/vkontakte_disabled.png",  :height => 16, :width => 16, :class => "disabled"